### ISSUE TITLE
Crash while setting level solver to solve the example level

### ISSUE THREAD

**Issue by thewitchhhh** [LotemDeNub/GLProject#1]
Here is the crash log:

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.d3d.D3DGeneralBlit.Blit(Unknown Source)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageCopy(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at com.gl.graphics.GraphicUtils.drawImage(GraphicUtils.java:41)
	at com.gl.game.PlayerMove.drawCorner(PlayerMove.java:130)
	at com.gl.game.PlayerMove.draw(PlayerMove.java:280)
	at com.gl.game.tiles.GameTile.drawPlayerMove(GameTile.java:253)
	at com.gl.game.GameLevel.draw(GameLevel.java:215)
	at com.gl.views.game_view.GamePanel.paintComponent(GamePanel.java:122)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)

**Comment by LotemBY** [comment]
Do you have the level export by any chance?
Or do you remember what was the level size, the amount of players, and if it was actually solvable?

**Comment by thewitchhhh** [comment]
I was using the level example in the project folder.

**Comment by LotemBY** [comment]
Oh ye right, I didn't read the title correctly ;)

To help me understand the problem, can you run the jar from console using:
`java -Xmx1024m -jar GLProject_v0.1.1.jar`
This should allocate bigger heap for the program (If this doesn't work, try to change the 1024 in the command).

Also, can you run `java -XX:+PrintFlagsFinal -version | findstr HeapSize` and send me the output?
(https://stackoverflow.com/questions/4667483)

**Comment by thewitchhhh** [comment]
Tried reproducing the crash, but I couldn't. The game froze though, on the seventh- or eight-try. 
Then it kept freezing every time I set it to solve the example level. Oh, it crashed now... Here's the log:
`java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.ArrayList.grow(Unknown Source)
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
	at java.util.ArrayList.addAll(Unknown Source)
	at com.gl.game.PlayerMove.<init>(PlayerMove.java:32)
	at com.gl.game.GamePlayer.<init>(GamePlayer.java:41)
	at com.gl.game.GameLevel.<init>(GameLevel.java:63)
	at com.gl.generation.Solver.solveStateWithPlayers(Solver.java:141)
	at com.gl.generation.Solver.lambda$startSolving$1(Solver.java:156)
	at com.gl.generation.Solver$$Lambda$80/6041617.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

When inputing: `java -Xmx1024m -jar GLProject_v0.1.1.jar`
I get: `Error: Unable to access jarfile GLProject_v0.1.1.jar`


When running: `java -XX:+PrintFlagsFinal -version | findstr HeapSize` 
This was the output:  
    `uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 67108864                            {product}
    uintx InitialHeapSize                          := 16777216                            {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 268435456                           {product}
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) Client VM (build 25.171-b11, mixed mode)`
